name=Small Keyboard Library
version=0.0.1
sentence=For small keyboard and keypad
paragraph=Support CH552
author=Takeshi Higasa
maintainer=okiraku-camera.tokyo
url=https://okiraku-camera.tokyo/
category=Other
architecture=*